name: 'technews'

services:

  postgres:
    build: postgresql/
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    restart: always
  
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - .:/app
    command: ./wait-for-it.sh postgres:5432 -- ./docker-entrypoint.sh 

  celery:
    build: .
    depends_on:
      - redis
      - api
      - postgres
    volumes:
      - .:/app
    command: ./wait-for-it.sh postgres:5432 -- celery -A TechNews worker --loglevel=info

  celery-beat:
    build: .
    depends_on:
      - redis
      - api
      - postgres
    volumes:
      - .:/app
    command: ./wait-for-it.sh postgres:5432 -- celery -A TechNews beat --loglevel=info

  flower:
    build: .
    depends_on:
      - api
      - redis
      - celery
      - postgres
    environment:
      - CELERY_BROKER=${CELERY_BROKER_URL}
      - CELERY_BACKEND=${CELERY_BROKER_URL}
    ports:
      - 5555:5555
    command: ./wait-for-it.sh postgres:5432 -- celery -A TechNews flower

volumes:
  postgres-data:
