# Generated by Django 5.1 on 2024-08-17 20:11

import news.utils.persian_calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_text_alter_news_title_alter_tag_tag_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(blank=True, default=news.utils.persian_calendar.PersianCalendar.currnet_persian_datetime, null=True),
        ),
    ]
